# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Pi Security
# Generated by the Sloane CLI formula generator.
class Sloane < Formula
  desc "Pi CLI: Sloane in your terminal and development workflow"
  homepage "https://github.com/pi-sloane/cli"
  version "0.6.17"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/pi-sloane/cli/releases/download/v0.6.17/sloane-darwin-arm64.zip"
      sha256 "995d7793c907f4c5e93e761578fe4a0e4e2f7867fdf7846941bcc8babf149175"
    else
      url "https://github.com/pi-sloane/cli/releases/download/v0.6.17/sloane-darwin-x64.zip"
      sha256 "5f64890aade286700ac4b06468e4e7838d1db4451266b6996a3910b53a96ad18"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/pi-sloane/cli/releases/download/v0.6.17/sloane-linux-arm64.tar.gz"
      sha256 "ad24928e30f2f03a8911b182479c5cd79099a1ee14339f1f8acb7f769bab625e"
    else
      url "https://github.com/pi-sloane/cli/releases/download/v0.6.17/sloane-linux-x64.tar.gz"
      sha256 "70abe1ce476eb160a90756c7fa884e484abf40e49b8888809f5c3733ada214eb"
    end
  end

  def install
    bin.install "sloane"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/sloane --version")
  end
end
