# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Pi Security
# Generated by the Sloane CLI formula generator.
class Sloane < Formula
  desc "Pi CLI: Sloane in your terminal and development workflow"
  homepage "https://github.com/pi-sloane/cli"
  version "0.6.28"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/pi-sloane/cli/releases/download/v0.6.28/sloane-darwin-arm64.zip"
      sha256 "d9e56e72baed45d9f57a436b3fd42f7033c04f1c30d37c9b694157c4b18bd28d"
    else
      url "https://github.com/pi-sloane/cli/releases/download/v0.6.28/sloane-darwin-x64.zip"
      sha256 "7df32137bd3ffd600fe1e954217b02c6e014f9cb19f1a7b6e635e3e2ce551ec9"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/pi-sloane/cli/releases/download/v0.6.28/sloane-linux-arm64.tar.gz"
      sha256 "26fdf5c2b784ac25813f221d2af80cfcca49d4eaf5209de3bfcb19e8d6432570"
    else
      url "https://github.com/pi-sloane/cli/releases/download/v0.6.28/sloane-linux-x64.tar.gz"
      sha256 "c3993a6230c37b47bf42f7424bdee77f39927c6e32a84514ea068fecac318f31"
    end
  end

  def install
    bin.install "sloane"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/sloane --version")
  end
end
