# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Pi Security
# Generated by the Sloane CLI formula generator.
class Sloane < Formula
  desc "Pi CLI: Sloane in your terminal and development workflow"
  homepage "https://github.com/pi-sloane/cli"
  version "0.6.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/pi-sloane/cli/releases/download/v0.6.6/sloane-darwin-arm64.zip"
      sha256 "b3395d1139e9155bd376826efaaecf3a7c9a49eebcdae112e41dbf60a69ae6fe"
    else
      url "https://github.com/pi-sloane/cli/releases/download/v0.6.6/sloane-darwin-x64.zip"
      sha256 "fc55afb5d035590559c7188c802bf3aedfa6b7ce2a96999eb09e442a7df612ed"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/pi-sloane/cli/releases/download/v0.6.6/sloane-linux-arm64.tar.gz"
      sha256 "a8c72aacf4a8b79ef23dc09f22bf211c6b555f7a2c7b6454a75f088dc29bb0bc"
    else
      url "https://github.com/pi-sloane/cli/releases/download/v0.6.6/sloane-linux-x64.tar.gz"
      sha256 "781bfcd264f56b6b1755f157e3f0964afd6c2fc3a6738ecdafe2365c9a704308"
    end
  end

  def install
    bin.install "sloane"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/sloane --version")
  end
end
